CREATE TABLE departamento (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(60) NOT NULL,
  telefone VARCHAR(45) NULL,
  responsavel VARCHAR(65) NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX nome_UNIQUE (nome ASC))
ENGINE = InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE empresa (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(60) NOT NULL,
  cnpj VARCHAR(45) NULL,
  telefone VARCHAR(45) NULL,
  email VARCHAR(45) NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB DEFAULT CHARSET=utf8;